### ISSUE TITLE
XPathResult is not defined

### ISSUE THREAD

**Issue by AlexBroadbent** [kabeleced77/dom#3]
My code compiles okay, but at runtime I get the error:

```
ReferenceError: XPathResult is not defined

    at ElementsByXPath.elements (/Users/user/repo/node_modules/@kabeleced/dom/dist/ElementsByXPath.js:23:100)
    at Client.parseResponse (/Users/user/repo/client.ts:111:31)
```

From what I read online, I had to add `dom` to the `compilerOptions.lib` list in `tsconfig.json`, but that hasn't resolved the issue.

I have `xmldom` in my `package.json` too, which I thought would resolve the issue. 

Am I missing anything or is there a missing dependency in this repository?

**Comment by kabeleced77** [comment]
Hi,
I do not really understand the problem. You run your application and `XPathResult` is not defined. As `XPathResult` "comes" the runtime I do not know what I could do from this repository.

What is your runtime? Where do you execute your application in?

**Comment by AlexBroadbent** [comment]
It's in a Node project, I have the `dom` library included but for some reason it isn't included at runtime.

I'm new to TypeScript so there's probably something obvious I am missing here.

**Comment by kabeleced77** [comment]
A quite good explanation can be found [here](https://stackoverflow.com/questions/6657216/why-doesnt-node-js-have-a-native-dom). TL;DR;: NodeJs has no native DOM support.

The methods of this `@kabeleced77/dom` module expect a DOM-`document` object. Using this module inside a browser environment (like an add-on), this should not be a problem. If this module is used within a Node.Js thouhg, you have to consider that there is no native DOM support. 

Following modules could be of help:
- [jsdom](https://www.npmjs.com/package/jsdom)
- [jsdom-global](https://www.npmjs.com/package/jsdom-global)

In your TypeScript code you should do the following

1. On top register both modules
```
import { JSDOM } from "jsdom";
import "jsdom-global/register";
```
2. Use `JSDOM` creating a virtual `DOM` with your "content"
```
let dom = new JSDOM(`<p id = "test-id"/p>`);
```
3. Following a complete TypeScript example
```
import { ElementsByXPath } from "@kabeleced/dom";
import { JSDOM } from "jsdom";
import "jsdom-global/register";

let dom = new JSDOM(`<p id = "test-id"/p>`);

const elementsByXPath = new ElementsByXPath('//*[@id="test-id"]');
console.log(elementsByXPath.xPath()); // should be
console.log(elementsByXPath.elements(dom.window.document)[0].tagName); // should be 'P'
```
4. Compile it and let it run
```
$ tsc test.ts && node test.js
//*[@id="test-id"]
P
```
